# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insms',
            options={'verbose_name_plural': 'Insms'},
        ),
        migrations.AlterModelOptions(
            name='outsms',
            options={'verbose_name_plural': 'Outsms'},
        ),
        migrations.AlterModelTable(
            name='insms',
            table='Insms',
        ),
        migrations.AlterModelTable(
            name='outsms',
            table='Outsms',
        ),
    ]
