# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twittersearch', '0002_auto_20160924_1002'),
        ('sms', '0002_auto_20160928_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twittersearch.Topics')),
            ],
            options={
                'db_table': 'Sms',
                'verbose_name_plural': 'Sms',
            },
        ),
        migrations.AlterField(
            model_name='outsms',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
