# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20160930_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insms',
            old_name='recieved_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='insms',
            name='messageidnumber',
            field=models.CharField(default=datetime.datetime(2016, 10, 29, 15, 30, 54, 825995, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
