# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20161029_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='insms',
            name='polarity',
            field=models.CharField(default=datetime.datetime(2016, 11, 7, 13, 57, 13, 784065, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
