# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_insms_polarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insms',
            old_name='messageidnumber',
            new_name='keyword',
        ),
    ]
