# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20161107_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insms',
            old_name='reciever',
            new_name='to',
        ),
    ]
