# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_auto_20161107_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insms',
            name='polarity',
            field=models.FloatField(max_length=255),
        ),
    ]
