# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_auto_20161107_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='subscribed_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
