# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20161122_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklistsms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Blacklistsms',
                'verbose_name_plural': 'Blacklistsms',
            },
        ),
        migrations.CreateModel(
            name='Failedsms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Failedsms',
                'verbose_name_plural': 'Failedsms',
            },
        ),
    ]
