# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-08 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_blacklistsms_failedsms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outsms',
            options={'get_latest_by': 'sent_date', 'verbose_name_plural': 'Outsms'},
        ),
    ]
