# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-08 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_auto_20170208_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistsms',
            options={'get_latest_by': 'sent_date', 'verbose_name_plural': 'Blacklistsms'},
        ),
        migrations.AlterModelOptions(
            name='failedsms',
            options={'get_latest_by': 'sent_date', 'verbose_name_plural': 'Failedsms'},
        ),
        migrations.AlterModelOptions(
            name='insms',
            options={'get_latest_by': 'date', 'verbose_name_plural': 'Insms'},
        ),
    ]
