# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_auto_20170208_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insms',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
