# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-11 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_auto_20170208_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='insms',
            name='message_id',
            field=models.IntegerField(default=38217146, max_length=255),
            preserve_default=False,
        ),
    ]
