# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-11 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_insms_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insms',
            name='message_id',
        ),
    ]
