# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_remove_insms_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='insms',
            name='msg_number',
            field=models.IntegerField(default=38217145, max_length=255),
            preserve_default=False,
        ),
    ]
