# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-11 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_insms_msg_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insms',
            name='msg_number',
        ),
    ]
