# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-11 21:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0021_auto_20170211_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insms',
            name='msg_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
