# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0022_auto_20170211_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='insms',
            name='msg_read_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insms',
            name='msg_type_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
