# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('polarity', models.FloatField(max_length=255)),
            ],
            options={
                'db_table': 'StreamTweets',
                'verbose_name_plural': 'StreamTweets',
            },
        ),
    ]
