# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-26 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterstream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamtweets',
            name='date',
        ),
    ]
