# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-30 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterstream', '0002_remove_streamtweets_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamtweets',
            name='pub_data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
