# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterstream', '0004_auto_20161130_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamtweets',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
