# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-07 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterstream', '0005_auto_20161207_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamtweets',
            name='date',
            field=models.DateField(),
        ),
    ]
