# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-09 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160924_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datefilters',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Datefilters',
                'verbose_name_plural': 'Datefilters',
            },
        ),
    ]
